# tools
required = [
  "gopkg.in/reform.v1/reform",

  "github.com/vektra/mockery/cmd/mockery",

  # We do not vendor promtool. See https://jira.percona.com/browse/PMM-2182
  # "github.com/prometheus/prometheus/cmd/promtool",

  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
  "github.com/go-swagger/go-swagger/cmd/swagger"
]

[prune]
  go-tests = true

  # to keep google/api/annotations.proto
  # non-go = true
  # unused-packages = true

[[constraint]]
  # https://jira.percona.com/browse/PMM-1710
  # https://jira.percona.com/browse/PMM-3209
  name = "github.com/percona/kardianos-service"
  branch = "PMM-3209-supervisord-fixes-for-pmm-managed"

[[constraint]]
  # https://jira.percona.com/browse/PMM-1561
  name = "github.com/hashicorp/consul"
  version = "=0.8.5"

# TODO switch to tags before PMM 2.0 release
[[constraint]]
  name = "github.com/percona/pmm"
  branch = "PMM-2.0"
