ignored = [
  "gonum.org/v1/plot*"  # backoff_draw.go
]

# tools
required = [
  "github.com/BurntSushi/go-sumtype",
  "github.com/vektra/mockery/cmd/mockery",
  "golang.org/x/perf/cmd/benchstat",
  "golang.org/x/tools/cmd/goimports",
  "gopkg.in/reform.v1/reform",

  # for make gen-init when it is needed
  # "gopkg.in/reform.v1/reform-db",
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[prune.project]]
    name = "github.com/lfittl/pg_query_go"
    non-go = false
    unused-packages = false

[[constraint]]
  # FIXME Remove that explicit constraint once 1.4.3 is tagged.
  # See https://github.com/golang/protobuf/issues/1219
  name = "github.com/golang/protobuf"
  source = "github.com/cybrcodr/protobuf"
  revision = "3beb084e9a50bff8d7ac57f1c9aa41671f479cbd"

[[constraint]]
  name = "github.com/percona/pmm"
  branch = "PMM-2.0"

[[constraint]]
  name = "github.com/percona/go-mysql"
  branch = "PMM-2.0"

# to prevent unexpected downgrades
[[constraint]]
  name = "github.com/percona/exporter_shared"
  version = "0.7.2"
[[constraint]]
  name = "github.com/percona/percona-toolkit"
  version = "3.2.1"

# https://jira.percona.com/browse/PMM-4081
[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  branch = "v2.2.6-no-dots"
  source = "https://github.com/Percona-Lab/kingpin.git"

[[constraint]]
  name = "github.com/lfittl/pg_query_go"
  branch = "master"
  source = "https://github.com/Percona-Lab/pg_query_go"
