# tools
required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/mwitkow/go-proto-validators/protoc-gen-govalidators",
  "github.com/jteeuwen/go-bindata/go-bindata",
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
