# tools
required = [
  "github.com/quasilyte/go-consistent",
  "golang.org/x/tools/cmd/goimports",
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

# TODO switch to tags before PMM 2.0 release
[[constraint]]
  name = "github.com/percona/pmm"
  branch = "PMM-2.0"

# TODO Remove when v1.1.0 is released.
# https://github.com/AlekSi/pointer/milestone/1
[[constraint]]
  name = "github.com/AlekSi/pointer"
  branch = "develop"

# https://jira.percona.com/browse/PMM-4081
# https://jira.percona.com/browse/PMM-4042
[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  branch = "v2.2.6-percona"
  source = "https://github.com/Percona-Lab/kingpin.git"
