# tools
required = [
  "gopkg.in/reform.v1/reform",

  "github.com/vektra/mockery/cmd/mockery",

  # We do not vendor promtool. See https://jira.percona.com/browse/PMM-2182
  # "github.com/prometheus/prometheus/cmd/promtool",

  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
  "github.com/go-swagger/go-swagger/cmd/swagger"
]

[prune]
  go-tests = true

  # to keep google/api/annotations.proto
  # non-go = true
  # unused-packages = true

[[constraint]]
  # this branch is not merged yet
  # https://jira.percona.com/browse/PMM-1710
  name = "github.com/percona/kardianos-service"
  branch = "PMM-1710-supervisord"

[[constraint]]
  # https://jira.percona.com/browse/PMM-1561
  name = "github.com/hashicorp/consul"
  version = "=0.8.5"

[[constraint]]
  # 0.13.0 is broken
  # https://github.com/go-swagger/go-swagger/pull/1285
  name = "github.com/go-swagger/go-swagger"
  version = "=0.12.0"
