# tools
required = [
  "gopkg.in/reform.v1/reform",

  "github.com/vektra/mockery/cmd/mockery",

  # We do not vendor promtool. See https://jira.percona.com/browse/PMM-2182
  # "github.com/prometheus/prometheus/cmd/promtool"
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

# TODO switch to tags before PMM 2.0 release
[[constraint]]
  name = "github.com/percona/pmm"
  branch = "PMM-2.0"

[[constraint]]
  # Stick to 0.9.x for now.
  # https://github.com/prometheus/client_golang#important-note-about-releases-versioning-tagging-and-stability
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

# TODO Remove when v1.1.0 is released.
# https://github.com/AlekSi/pointer/milestone/1
[[constraint]]
  name = "github.com/AlekSi/pointer"
  branch = "develop"
