# tools
required = [
  "github.com/BurntSushi/go-sumtype",
  "github.com/kevinburke/go-bindata/go-bindata",
  "github.com/vektra/mockery/cmd/mockery",
  "golang.org/x/tools/cmd/goimports",
  "gopkg.in/reform.v1/reform",
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/percona/pmm"
  branch = "release/2.16"

[[constraint]]
  name = "github.com/percona-platform/saas"
  branch = "main"

[[constraint]]
  name = "github.com/percona-platform/dbaas-api"
  branch = "pmm-2.16"
