required = [
  # tools
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/mwitkow/go-proto-validators/protoc-gen-govalidators",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
  "github.com/go-openapi/runtime/client",
  "github.com/go-openapi/spec",
  "github.com/go-swagger/go-swagger/cmd/swagger",
  "github.com/BurntSushi/go-sumtype",
  "github.com/Percona-Lab/swagger-order",

  # require key dependencies explicitly to make dep work
  "github.com/golang/protobuf/proto",
  "google.golang.org/grpc",
  "github.com/grpc-ecosystem/grpc-gateway/runtime",
  "github.com/go-swagger/go-swagger",
  "github.com/sirupsen/logrus",
  "github.com/stretchr/testify"
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

# to keep *.proto files
[[prune.project]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  non-go = false
  unused-packages = false
[[prune.project]]
  name = "github.com/mwitkow/go-proto-validators"
  non-go = false
  unused-packages = false

# We want all PMM components to use the same versions of key dependecies to avoid nasty suprises.

[[constraint]]
  name = "github.com/pkg/errors"
  version = "=0.9.1"
[[constraint]]
  # FIXME Update to 1.4.3 once it is tagged. See https://github.com/golang/protobuf/issues/1219
  name = "github.com/golang/protobuf"
  source = "github.com/cybrcodr/protobuf"
  revision = "3beb084e9a50bff8d7ac57f1c9aa41671f479cbd"
[[constraint]]
  name = "google.golang.org/protobuf"
  version = "=1.25.0"
[[constraint]]
  name = "google.golang.org/grpc"
  version = "=1.32.0"
[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "=1.15.0"
[[constraint]]
  # https://github.com/go-openapi/spec/pull/109 will not be merged, so we need to maintain our fork.
  # See https://jira.percona.com/browse/PMM-4934.
  name = "github.com/go-openapi/spec"
  source = "github.com/Percona-Lab/spec"
  version = "=0.19.8-percona"
[[constraint]]
  name = "github.com/go-swagger/go-swagger"
  version = "=0.24.0"
[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "=1.6.0"
[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=1.6.1"
[[constraint]]
  # v1.2.0+ uses github.com/cespare/xxhash/v2 module, but dep can't handle v2+ modules
  name = "github.com/prometheus/client_golang"
  version = "=1.1.0"
