# tools
required = [
  "github.com/kevinburke/go-bindata/go-bindata",
  "golang.org/x/tools/cmd/goimports",
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/percona/pmm"
  branch = "PMM-5727"

[[constraint]]
  name = "github.com/percona/go-mysql"
  branch = "PMM-2.0"
