# tools
required = [
  "github.com/BurntSushi/go-sumtype",
  "github.com/vektra/mockery/cmd/mockery",
  "golang.org/x/tools/cmd/goimports",
  "gopkg.in/reform.v1/reform",

  # We do not vendor promtool. See https://jira.percona.com/browse/PMM-2182
  # "github.com/prometheus/prometheus/cmd/promtool"
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/percona/pmm"
  branch = "PMM-2.0"
