---
# This playbook contains tasks executed during PMM Server update.

- hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    # See https://github.com/Supervisor/supervisor/issues/1264 for explanation
    # why we do reread + stop/remove/add instead of using supervisorctl Ansible module.

    - name: Reread supervisord configuration
      command: supervisorctl reread
      register: reread_result
      changed_when: "'No config updates to processes' not in reread_result.stdout"

    - name: Check reread results
      debug: var=reread_result.stdout_lines

    # split download and update to produce a bit more of progress output
    - name: Download packages
      yum:
        name: '*'
        state: latest
        download_only: yes 
    - name: Update packages
      yum:
        name: '*'
        state: latest

    # restart pmm-managed first as it may update supervisord configuration on start
    - name: Restart pmm-managed
      command: supervisorctl {{ item }} pmm-managed
      changed_when: True
      with_items: ['stop', 'remove', 'add']

    # give pmm-managed time to update supervisord configuration,
    # and give update UI time to catch up after pmm-managed restart
    - name: Wait for pmm-managed
      pause: seconds=5

    - name: Reread supervisord configuration again
      command: supervisorctl reread
      register: reread_result
      changed_when: "'No config updates to processes' not in reread_result.stdout"

    - name: Check reread results
      debug: var=reread_result.stdout_lines

    - name: Restart services
      command: supervisorctl {{ item.1 }} {{ item.0 }}
      changed_when: True
      with_nested:
        - - nginx
          - postgresql
          - prometheus
          - clickhouse
          - grafana
          - qan-api2
          - pmm-agent
        - ['stop', 'remove', 'add']

    - name: Update Grafana dashboards
      command: supervisorctl start dashboard-upgrade
      changed_when: True

    - name: Update/restart other services
      command: supervisorctl update
      register: update_result
      changed_when: "'updated' in update_result.stdout"

    - name: Check other services
      debug: var=update_result.stdout_lines

    # SIGUSR2 is sent to supervisord by pmm-managed right before the update to for logging to work correctly.
    # We use that fact to show what was restarted during the update.
    - name: Get supervisord log
      shell: supervisorctl maintail -100000 | tac | awk '!flag; /received SIGUSR2/{flag = 1};' | tac
      register: maintail_result
      changed_when: False

    - name: Check supervisord log
      debug: var=maintail_result.stdout_lines
