---
# This role contains tasks executed during initialization PMM Server
- name: Get current version
  slurp:
    src: /srv/grafana/PERCONA_DASHBOARDS_VERSION
  register: current_version_file
  ignore_errors: True

- name: Get image version
  slurp:
    src: /usr/share/percona-dashboards/VERSION
  register: image_version_file

- name: Set current version if VERSION fail doen't exist
  set_fact:
      pmm_current_version: "0.0"
  when: current_version_file['failed'] == true

- name: Setting current and image version
  set_fact:
    pmm_current_version: "{{ current_version_file['content'] | b64decode | trim }}"
  when: current_version_file['failed'] != true

- name: Setting current and image version
  set_fact:
    pmm_image_version: "{{ image_version_file['content'] | b64decode | trim }}"

- name: Print current version
  debug:
    msg: "Current version: {{ pmm_current_version }} Image Version: {{ pmm_image_version }}"

- name: Checking if we need an update or not
  include_role:
    name: dashboards_upgrade
  when: not pmm_current_version is version(pmm_image_version, '>=')

- name: Create backup directory
  file:
    path: /srv/backup
    state: directory

- name: Wait until postgres socket is present before continuing
  wait_for:
    path: /var/run/postgresql/.s.PGSQL.5432

- name: Get postgres encoding
  postgresql_query:
    db: pmm-managed
    query: SHOW SERVER_ENCODING;
  register: postgres_encoding
  become: yes
  become_user: postgres
  become_method: su

- debug:
    var: postgres_encoding.query_result

- name: Change encoding of pmm-managed database
  include_role:
    name: postgres-ascii-to-utf8
  when: "'SQL_ASCII' == postgres_encoding.query_result[0].server_encoding"
