site_name: Percona Monitoring and Management
#site_url: https://www.percona.com/doc/percona-monitoring-and-management/1.x/
repo_name: percona/pmm
repo_url: https://github.com/percona/pmm
edit_uri: edit/master/doc/markdown/
site_description: Percona Monitoring and Management Documentation
site_author: Percona LLC
copyright: Percona LLC, &#169; 2020
use_directory_urls: false
docs_dir: docs
#strict: true

theme:
  name: material
  custom_dir: theme
  language: en
  palette:
    primary: deep-orange
    accent: white
  font:
    text: Chivo
    code: Roboto Mono
  logo: _images/pmm-doc-logo.svg
  favicon: _images/percona_favicon.ico

extra_css:
  - https://unicons.iconscout.com/release/v3.0.3/css/line.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css

markdown_extensions:
    - toc:
        baselevel: 1
        toc_depth: "2-3"
        anchorlink: True
    - admonition
    - def_list
    - smarty:
        smart_angled_quotes: True
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tabbed
    - pymdownx.tilde
    - pymdownx.superfences
    - pymdownx.highlight:
        linenums: false
    - plantuml_markdown

plugins:
    - search
    - git-revision-date
    - macros:
        include_yaml: # Variables used in Markdown and templates as '{{ VAR }}'
          - 'icon.yml'    # Icon shortcuts
          - 'release.yml' # PMM release and version numbers {{ icon.<name> }}
          - 'extra.yml'   # Everything else
    - exclude:
        glob:
          - deploy/client/apt.md # Was orphan in sphinx - content moved
          - deploy/client/yum.md
          - use-case.mysql-slow-log-rotation.md # Added to conf-mysql
          - use-case.external-monitoring-service.postgresql.rds.md # Added to conf-postgres

extra: # Used in main.html template and can't be externalised
  open_issue_text: '<i class="uil uil-exclamation-triangle"></i> Report a problem with this page'
  open_issue_subject: 'PMM doc issue on page '
  open_issue_body: 'Please describe the issue here'
  open_issue_tooltip: 'Report an issue with this page on GitHub'
  edit_page_text: '<i class="uil uil-pen"></i> Edit this page'
  updated_text: '<i class="uil uil-refresh"></i> Page updated'

nav:
  - index.md
  - Basics:
    - 'Architecture Overview': 'architecture.md'
    - 'Deployment Instructions':
      - 'deploy/index.md'
      - 'Docker':
        - 'deploy/server/docker.md'
        - 'deploy/server/docker.setting-up.md'
        - 'deploy/server/docker.upgrading.md'
        - 'deploy/server/docker.backing-up.md'
        - 'deploy/server/docker.restoring.md'
      - 'Virtual Appliance':
        - 'deploy/server/virtual-appliance.md'
        - 'deploy/server/ova.virtualbox.cli.md'
        - 'deploy/server/ova.virtualbox.gui.md'
        - 'deploy/server/ova.vmware-workstation-player.md'
      - 'deploy/server/ami.md'
    - 'Tools of PMM':
      - 'tool.md'
      - 'qan.md'
      - 'metrics-monitor.md'
  - 'Advanced':
    - 'pmm-admin.md'
    - 'remote-instance.md'
    - 'amazon-rds.md'
    - 'conf-mysql.md'
    - 'conf-postgres.md'
    - 'conf-mongodb.md'
    - 'security.md'
    - 'Metrics Monitor Dashboards':
      - 'index.metrics-monitor.dashboard.md'
      - dashboard.home.md
      - dashboard.pmm-system-summary.md
      - dashboard.advanced-data-exploration.md
      - dashboard.cross-server-graphs.md
      - dashboard.summary.md
      - dashboard.trends.md
      - dashboard.network-overview.md
      - dashboard.cpu-utilization-details-cores.md
      - dashboard.disk-space.md
      - dashboard.system-overview.md
      - dashboard.compare-system-parameters.md
      - dashboard.overview-numa-metrics.md
      - dashboard.prometheus.md
      - dashboard.prometheus-exporter-status.md
      - dashboard.prometheus-exporters-overview.md
      - dashboard.mysql-amazon-aurora-metrics.md
      - dashboard.mysql-command-handler-counters-compare.md
      - dashboard.mysql-innodb-compression.md
      - dashboard.mysql-innodb-metrics.md
      - dashboard.mysql-innodb-metrics-advanced.md
      - dashboard.mysql-myisam-aria-metrics.md
      - dashboard.mysql-myrocks-metrics.md
      - dashboard.mysql-overview.md
      - dashboard.mysql-performance-schema.md
      - dashboard.mysql-performance-schema-wait-events.md
      - dashboard.mysql-query-response-time.md
      - dashboard.mysql-replication.md
      - dashboard.mysql-table-statistics.md
      - dashboard.mysql-user-statistics.md
      - dashboard.mongodb-cluster-summary.md
      - dashboard.mongodb-inmemory.md
      - dashboard.mongodb-mmapv1.md
      - dashboard.mongodb-overview.md
      - dashboard.mongodb-replset.md
      - dashboard.mongodb-rocksdb.md
      - dashboard.mongodb-wiredtiger.md
      - dashboard.postgres-overview.md
      - dashboard.pxc-galera-cluster-overview.md
  - 'Reference':
    - 'Release Notes':
        - 'release-notes/index.md'
        - 'release-notes/1.17.4.md'
        - 'release-notes/1.17.3.md'
        - 'release-notes/1.17.2.md'
        - 'release-notes/1.17.1.md'
        - 'release-notes/1.17.0.md'
        - 'release-notes/1.16.0.md'
        - 'release-notes/1.15.0.md'
        - 'release-notes/1.14.1.md'
        - 'release-notes/1.14.0.md'
        - 'release-notes/1.13.0.md'
        - 'release-notes/1.12.0.md'
        - 'release-notes/1.11.0.md'
        - 'release-notes/1.10.0.md'
        - 'release-notes/1.9.1.md'
        - 'release-notes/1.9.0.md'
        - 'release-notes/1.8.1.md'
        - 'release-notes/1.8.0.md'
        - 'release-notes/1.7.0.md'
        - 'release-notes/1.6.1.md'
        - 'release-notes/1.6.0.md'
        - 'release-notes/1.5.3.md'
        - 'release-notes/1.5.2.md'
        - 'release-notes/1.5.1.md'
        - 'release-notes/1.5.0.md'
        - 'release-notes/1.4.1.md'
        - 'release-notes/1.4.0.md'
        - 'release-notes/1.3.2.md'
        - 'release-notes/1.3.1.md'
        - 'release-notes/1.3.0.md'
        - 'release-notes/1.2.2.md'
        - 'release-notes/1.2.1.md'
        - 'release-notes/1.2.0.md'
        - 'release-notes/1.1.5.md'
        - 'release-notes/1.1.4-2.md'
        - 'release-notes/1.1.4.md'
        - 'release-notes/1.1.3.md'
        - 'release-notes/1.1.2.md'
        - 'release-notes/1.1.1.md'
        - 'release-notes/1.1.0beta.md'
        - 'release-notes/1.0.7.md'
        - 'release-notes/1.0.6.md'
        - 'release-notes/1.0.5.md'
        - 'release-notes/1.0.4.md'
        - 'release-notes/1.0.3.md'
        - 'release-notes/1.0.2.md'
        - 'release-notes/1.0.1.md'
        - 'release-notes/1.0.0.md'
    - 'Exporters':
      - index.exporter-option.md
      - section.exporter.mongodb.md
      - section.exporter.mysqld.md
      - section.exporter.node.md
      - section.exporter.proxysql.md
      - section.exporter.rds.md
    - 'Contact Us': 'contact.md'
    - 'FAQ': 'faq.md'
    - 'Glossaries':
      - 'index.glossary.md'
      - 'glossary.option.md'
      - 'glossary.terminology.md'
