---
version: '3'
services:
  pmm-admin-server:
    image: ${PMM_SERVER_IMAGE:-percona/pmm-server:3}
    container_name: pmm-admin-server
    environment:
      - PATH=/root/go/bin:$PATH
      - REVIEWDOG_GITHUB_API_TOKEN=${REVIEWDOG_GITHUB_API_TOKEN} 
