# v2.0.0
---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: PMM                        | Stat supervisor
      stat: path=/usr/bin/supervisorctl
      register: supervisorctl

    - name: PMM                        | Clean YUM cache
      command: /usr/bin/yum --enablerepo=pmm clean all
      changed_when: False

    - name: PMM                        | Remove RPMs
      when: ansible_os_family == 'RedHat'
      yum: name={{ item }} state=absent
      with_items:
        - percona-qan-app2
        - percona-node_exporter-0.13.0

    - name: PMM                        | Stat purge-qan-data backup
      stat: path=/srv/update/purge-qan-data-backup
      register: purge_qan_data_backup

    - name: PMM                        | Backup unmanaged configs
      when: not purge_qan_data_backup.stat.exists
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: '/etc/orchestrator.conf.json',    dest: '/srv/update/orchestrator.conf.json-backup' }
        - { src: '/etc/cron.daily/purge-qan-data', dest: '/srv/update/purge-qan-data-backup' }
        - { src: '/etc/grafana/grafana.ini',       dest: '/srv/update/grafana-backup' }

    - name: Data partition             | Create a file for changing partitions
      when: ansible_lvm is defined
      copy:
        content: |
          #!/bin/sh

          set -o errexit

          /usr/sbin/pvresize $(/usr/bin/ls /dev/sda /dev/sdb /dev/sdc /dev/xvdb /dev/nvme1n1 2>/dev/null | /usr/bin/grep -v ^$(/usr/sbin/pvdisplay -c | /usr/bin/grep ':VolGroup00:' | /usr/bin/cut -d ':' -f 1 | /usr/bin/tr -d '[:space:]' | /usr/bin/sed 's/[0-9]$//')$ | /usr/bin/grep -v ^$(/usr/bin/findmnt -f -n -o SOURCE / | /usr/bin/sed 's/[0-9]$//')$ | /usr/bin/grep -v ^$(/usr/bin/findmnt -f -n -o SOURCE /mnt/resource | /usr/bin/sed 's/[0-9]$//')$)
          /usr/sbin/lvextend -l '1%VG' /dev/DataVG/ThinPool_tmeta
          /usr/sbin/lvextend -l '100%VG' /dev/DataVG/ThinPool
          /usr/sbin/lvextend -l '80%VG' /dev/DataVG/DataLV
          /usr/sbin/xfs_growfs -d /srv
        dest: /var/lib/cloud/scripts/per-boot/resize-xfs
        force: yes
        mode: 0755

    - stat: path=/var/lib/cloud/scripts/per-boot/resize-xfs
      register: resizeXfs

    - name: Cron tasks                 | Add partition resize task to cron
      when: resizeXfs.stat.exists == True
      cron:
        name: "resize data partition"
        minute: "*/5"
        user: root
        job: "/var/lib/cloud/scripts/per-boot/resize-xfs"
        cron_file: resizeXfs

    - name: PMM                        | Update pmm-server RPM
      when: ansible_os_family == 'RedHat'
      yum: name={{ item }} state=present enablerepo=pmm
      with_items:
        - pmm-server-2.0.0
      register: pmm_server_update
      failed_when: "pmm_server_update | failed and 'Error in PREUN scriptlet in rpm package pmm-server' not in pmm_server_update.msg"

    - name: NGINX                      | Disable password-page
      when: supervisorctl.stat.exists
      replace:
        dest: /etc/nginx/conf.d/pmm.conf
        regexp: 'setup_type ovf-ami'
        replace: 'setup_type docker'

    - name: PMM                        | PMM-1826 Remove broken 1.5.0 rpms
      command: sh -c "/usr/bin/rpm --erase --noscripts pmm-server-1.5.0 || :"

    - name: PMM                        | PMM-1826 Remove broken 1.5.1 rpms
      command: sh -c "/usr/bin/rpm --erase --noscripts pmm-server-1.5.1 || :"

    - name: PMM                        | Remove broken percona-dashboards rpm
      when: ansible_os_family == 'RedHat' and image_creation is not defined
      yum: name={{ item }} state=absent enablerepo=pmm
      with_items:
        - percona-dashboards

    - name: PMM                        | Install RPMs
      when: ansible_os_family == 'RedHat'
      yum: name={{ item }} state=latest enablerepo=pmm
      with_items:
        - nginx-1.15.8
        - pmm-update
        - percona-toolkit-3.0.10
        - percona-dashboards-2.0.0
        - pmm-server-2.0.0
        - pmm-client-2.0.0
        - percona-orchestrator-3.0.6
        - percona-prometheus-2.3.2
        - percona-qan-api2-2.0.0
        - percona-grafana-5.1.3
        - percona-qan-app-2.0.0
        - pmm-manage-2.0.0
        - pmm-managed-2.0.0
        - rds_exporter-2.0.0

    - name: PMM                        | Restore unmanaged configs
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: '/srv/update/orchestrator.conf.json-backup', dest: '/etc/orchestrator.conf.json' }
        - { src: '/srv/update/purge-qan-data-backup',         dest: '/etc/cron.daily/purge-qan-data' }
        - { src: '/srv/update/grafana-backup',                dest: '/etc/grafana/grafana.ini' }

    - name: PMM                        | Remove temporary files
      command: /usr/bin/shred --remove /srv/update/orchestrator.conf.json-backup /srv/update/purge-qan-data-backup /srv/update/grafana-backup

    - name: PMM                        | Update entrypoint.sh
      when: supervisorctl.stat.exists
      copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
      with_items:
        - { src: '/usr/share/pmm-server/entrypoint.sh', dest: '/opt/entrypoint.sh', mode: 'u=rwx,g=rx,o=rx' }

    - name: PMM                        | Update supervisord config
      when: supervisorctl.stat.exists and image_creation is not defined
      command: /usr/bin/env UPDATE_MODE=1 ENABLE_DEBUG=1 /opt/entrypoint.sh

    - name: PMM                        | Restore configuration
      command: bash -c "/usr/bin/pmm-configure -grafana-db-path $(ls /srv/grafana/grafana.db /var/lib/grafana/grafana.db 2>/dev/null)"

    - name: qan-api                    | Fix QAN API DSN
      when: supervisorctl.stat.exists
      replace:
        dest: /etc/percona-qan-api.conf
        regexp: 'percona:percona'
        replace: 'qan-api:5goldenfipar'

    - name: qan-api                    | Fix QAN API DSN
      when: not supervisorctl.stat.exists
      replace:
        dest: /etc/percona-qan-api.conf
        regexp: 'qan-api:5goldenfipar'
        replace: 'percona:percona'

    - name: NGINX                      | Disable daemon
      when: supervisorctl.stat.exists
      lineinfile:
        dest: /etc/nginx/nginx.conf
        line: 'daemon off;'

    - name: NGINX                      | Fix nginx config
      replace:
        dest: /etc/nginx/nginx.conf
        regexp: '^(\s*)listen'
        replace: '\1#listen'

    - name: Security                   | Stat sshd_config
      stat: path=/etc/ssh/sshd_config
      register: sshd_config

    - name: Security                   | Disable root SSH access
      when: sshd_config.stat.exists
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present

    - name: Security                   | Remove percona key
      lineinfile:
        dest: /root/.ssh/authorized_keys
        regexp: '([Pp]acker|[Mm]ykola|[Pp]ercona)'
        state: absent

    - name: Security                   | Remove centos user
      when: keep_centos_user is not defined
      user:
        name: centos
        state: absent
        remove: yes

    - name: pmm-managed                | Create MySQL pmm-managed database
      mysql_db:
        name: pmm-managed
        state: present

    - name: pmm-managed                | Create MySQL pmm-managed user
      mysql_user:
        name: pmm-managed
        host: localhost
        password: '*816FFB19BC44AC2749D546E48FA0DF957EDB2C5A'
        priv: 'pmm-managed.*:ALL'
        encrypted: yes
        state: present

    - name: qan-api                    | Create MySQL user for Grafana
      mysql_user:
        name: grafana
        host: localhost
        password: '*58324E2D77A9BBFD9DD1E904649697615FE74649'
        priv: 'pmm.*:SELECT'
        encrypted: yes
        state: present

    - name: Hotfix                     | PMM-1232 Fix prometheus memory
      when: supervisorctl.stat.exists
      replace:
        dest: /etc/supervisord.d/pmm.ini
        regexp: '-storage.local.target-heap-size=268435456$'
        replace: '-storage.local.target-heap-size=766957568'

    - name: Grafana                    | Set snapshot server
      ini_file:
        dest: /etc/grafana/grafana.ini
        section: snapshots
        option: external_enabled
        value: true

    - name: Grafana                    | Set snapshot server
      ini_file:
        dest: /etc/grafana/grafana.ini
        section: snapshots
        option: external_snapshot_url
        value: https://snapshots-g504.percona.com

    - name: Grafana                    | Set snapshot server
      ini_file:
        dest: /etc/grafana/grafana.ini
        section: snapshots
        option: external_snapshot_name
        value: Share with Percona

    - name: Grafana                    | Enable gzip
      ini_file:
        dest: /etc/grafana/grafana.ini
        section: server
        option: enable_gzip
        value: true

    - name: Grafana                    | Enable Anonymous access
      ini_file:
        dest: /etc/grafana/grafana.ini
        section: auth.anonymous
        option: org_role
        value: Editor

    - name: PMM                        | Reload config (supervisord)
      when: supervisorctl.stat.exists
      command: /usr/bin/supervisorctl update

    - name: PMM                        | Restart orchestrator if needed
      when: supervisorctl.stat.exists
      command: sh -c '[[ "${ORCHESTRATOR_ENABLED}" = "true" ]] && /usr/bin/supervisorctl restart orchestrator || :'

    - name: PMM                        | Restart orchestrator if needed
      when: not supervisorctl.stat.exists
      command: /bin/systemctl condrestart orchestrator

    - name: PMM                        | Restart services (supervisord)
      when: supervisorctl.stat.exists
      command: /usr/bin/supervisorctl restart {{ item }}
      with_items:
        - prometheus
        - node_exporter
        - qan-api
        - grafana
        - pmm-managed

    - name: PMM                        | Restart services (systemd)
      when: not supervisorctl.stat.exists
      service: name={{ item }} state=restarted enabled=yes
      with_items:
        - prometheus
        - node_exporter
        - percona-qan-api
        - grafana-server
        - pmm-managed
        - sshd

    - name: PMM                        | Import dashboards
      command: bash -c "/usr/share/percona-dashboards/import-dashboards.py $(dirname $(ls /srv/grafana/grafana.db /var/lib/grafana/grafana.db 2>/dev/null))"
      register: import_result
      changed_when: "'up-to-date' not in import_result.stdout"

    - name: PMM                        | Restart pmm-manage daemon (delayed)
      shell: cd /tmp; nohup sh -c 'sleep 10; test -e /usr/bin/supervisorctl && /usr/bin/supervisorctl restart pmm-manage nginx || (/usr/sbin/nginx -s reload; /bin/systemctl restart pmm-manage)' </dev/null >/dev/null 2>&1 &
