name: BUILD PMM DOCS (2.x)

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: percona-platform/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: percona-platform/setup-python@v2
        with:
          python-version: "3.x"

      - name: Setup MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Setup PlantUML dependencies
        run: |
          sudo apt install -y graphviz

      - name: Configure git
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: |
          git config --global url."https://percona-platform-robot:${ROBOT_TOKEN}@github.com".insteadOf "https://github.com"
          git config user.name "GitHub Action"
          git config user.email "github-action@users.noreply.github.com"
          git config user.password "${ROBOT_TOKEN}"
          echo "GIT_USER=percona-platform-robot:${ROBOT_TOKEN}" >> $GITHUB_ENV

      # Builds theme-less static web site in 'publish' branch for percona.com
      - name: Run MkDocs (2.x)
        if: github.ref == 'refs/heads/main'
        run: |
          PATH=$PATH:_resources/bin mike deploy -F mkdocs-percona.yml 2.x -b publish -p
          mike retitle -F mkdocs-percona.yml 2.x "PMM2 (LATEST)" -b publish -p

      # Builds Material-themed static web site in 'netlify' branch for netlify.com
      - name: Run MkDocs for Netlify (2.x)
        if: github.ref == 'refs/heads/main'
        run: |
          PATH=$PATH:_resources/bin mike deploy 2.x -b netlify -p
          mike set-default 2.x -b netlify -p
          mike retitle 2.x "PMM2 (LATEST)" -b netlify  -p

      - name: Install Node.js 14.x
        uses: percona-platform/setup-node@v2.1.2
        with:
          node-version: "14"

      - name: Spelling
        run: |
          npx markdown-spellcheck --report --en-us --ignore-acronyms --ignore-numbers "docs/**/*.md" || true
          # Ignore errors, just inspect results

      - name: Grammar
        run: |
          npx write-good --no-passive docs/**/*.md || true
          # Ignore errors, just inspect results
