name: Linkspector
on: 
  pull_request:
    paths:
      - "documentation/**"

jobs:
  check-links:
    name: linkspector
    runs-on: ubuntu-22.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@3e12ade1e0b1823455dae8cf8b4f9cc92ec7dd20 # v1.3.3
        with:
          github_token: ${{ secrets.ROBOT_TOKEN || secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_level: error
          filter_mode: nofilter
          config_file: documentation/.linkspector.yml