name: Test podman.md

on:
  push:
    branches:
      - v3
  pull_request:
    paths:
      - 'documentation/docs/install-pmm/install-pmm-server/baremetal/podman/index.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Install pandoc
        run: |
          curl -O -sSfL https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb
          sudo apt-get install -y ./pandoc-2.18-1-amd64.deb
          rm pandoc-2.18-1-amd64.deb

      - name: Copy test template
        run: cp documentation/resources/bin/doc_test_template.sh ./documentation/docs_test_podman.sh

      - name: Get CodeBlocks and push them to test template
        run: pandoc -i documentation/docs/install-pmm/install-pmm-server/baremetal/podman/index.md --lua-filter documentation/resources/bin/CodeBlock.lua -t html -o /dev/null >> documentation/docs_test_podman.sh

      - name: Run podman tests
        run: ./documentation/docs_test_podman.sh

      - name: Get debug
        if: ${{ failure() }}
        run: |
          cat ./documentation/docs_test_podman.sh
          pandoc --version
          podman version
          podman ps --all
          systemctl --user status pmm-server.service || true
          podman inspect pmm-server || true
          journalctl --user -xe
